version: 2

# Accept tags with or without "v" prefix (e.g. "0.4" or "v0.4.0")
git:
  tag_sort: -version:refname
  prerelease_suffix: "-"
  ignore_tags:
    - nightly

before:
  hooks:
    - go mod tidy
    - go test ./... -timeout 5m

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X github.com/caeser1996/claude-switch/cmd.Version={{.Version}}
      - -X github.com/caeser1996/claude-switch/cmd.Commit={{.Commit}}
      - -X github.com/caeser1996/claude-switch/cmd.Date={{.Date}}
    binary: claude-switch

archives:
  # Standard compressed archives for manual download and install.sh
  - id: archive
    format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- .Os }}_
      {{- .Arch }}
    format_overrides:
      - goos: windows
        format: zip

  # Raw binaries used by `cs update` for self-updating
  # Named claude-switch_os_arch (+ .exe on Windows) with no version or extension
  - id: binary
    format: binary
    name_template: >-
      {{ .ProjectName }}_
      {{- .Os }}_
      {{- .Arch }}

checksum:
  name_template: "checksums.txt"

release:
  replace_existing_artifacts: true

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"
      - "^chore:"

brews:
  - ids:
      - archive
    repository:
      owner: caeser1996
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_TOKEN }}"
    directory: Formula
    homepage: "https://github.com/caeser1996/claude-switch"
    description: "CLI tool for managing multiple Claude Code accounts"
    license: "MIT"
    install: |
      bin.install "claude-switch"
      bin.install_symlink "claude-switch" => "cs"
    test: |
      system "#{bin}/claude-switch", "version"
